queue_rules:
  - name: default
    queue_conditions:
      - base=master
      - label="merge-when-passing"
      - label!="work-in-progress"
      - "approved-reviews-by=@flux-framework/core"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
      - -title~="^\[*(WIP|wip)"
    merge_conditions:
      - base=master
      - status-success="validate commits"
      - status-success="make check"
      - status-success="make linkcheck"
      - label="merge-when-passing"
      - label!="work-in-progress"
      - "approved-reviews-by=@flux-framework/core"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
      - -title~="^\[*(WIP|wip)"
    merge_method: merge
    update_method: rebase

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
