4/Flux Resource Model
=====================

The Flux Resource Model describes the conceptual model used for
resources within the Flux framework.

* Name: github.com/flux-framework/rfc/spec_4.adoc
* Editor: Mark Grondona <mgrondona@llnl.gov>
* State: raw

== Language

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD",
"SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to
be interpreted as described in http://tools.ietf.org/html/rfc2119[RFC 2119].

== Background

As in traditional resource management software, the Flux framework
requires a method for the description, configuration, tracking, and
assignment or consumable and other resources in the system being
managed. The Flux Framework, however, requires a more generalized and
flexible definition of resources and overall approach. This document
describes the basic reosurce model used by Flux, and how it relates
to other resource management components. We term the model for
describing resources in Flux _The Flux Resource Model_.

== Goals

The Flux Resource Model provides a common conceptual model for resources
described and managed by the Flux framework and its components. The
goals of this model are to:

* Develop a generalized, extensible model for resources within the framework
  such that all present and future resource types fit the model
* Provide a common configuration scheme for these resources
* Provide a common storage, access, modification and discovery APIs for
  managing resource information

== Related Specifications

== Design

The sections below describe in detail the Flux Resource Model
and its related specifications and APIs.

=== Conceptual Model: The Composite Resource Pool

The fundamental model for resources in the Flux framework is
the _composite resource pool_.  All resources MAY be modeled
using this concept, which is the combination of a _composite type_
(resources with 0 or more children arranged in a hierarchical
``has-a'' relationship), and a _resource pool_, which allows
the grouping of 1 or more _indistinct_ resources into a pool
with a given size.

This conceptual model leads to the natural representation of
resources in Flux as a hierarchy of individual or pooled resources
bound to a _root_ which will typically be a ``cluster'' or ``center''
resource. 

Use of the composite pool model for resources in Flux has the
following nice properties:

* Groups of related resources are treated the same as a single instance
* A subset of a composite resource pool is a valid composite resource pool
* Composite resource naturally describes resources in a ``has-a'' relationship
* High level resources can be created piece-wise from base resource types.

=== Composite Resource Pool Representation

The representation of resources within the Flux framework SHALL
allow resources to be modeled as _composite pools_, and thus SHALL
store basic resource _pool_ data (attributes of resource) as well
as _composite_ data (hierarchical parent/child or ``has-a'' relationship
between resources).  Data required to be stored, tracked, and queried
is detailed in sections below.

==== Resource pool data:

* Type
* UUID (Unique ID for this resource)
* Name or Basename
* ID (optional numeric ID to be appended to basename to get name)
* Properties (static properties associated with this instance)
* Tags (dynamic list of tags)
* Size (Total number of resources in this pool)
* Allocation table (List of active allocations from this pool with metadata)
* Hierarchy table (Hierarchies and topologies to which this resource belongs)

Resource pools MAY belong to one or more hierarchies. In Flux, the
``default'' hierarchy holds the _composite_ representation for resource
pools, though a resource MAY belong to more than a single hierarchy.

==== Resource hierarchy data:

* URI (in ``name:/path/to/resource'' form)
* Children
* Parent
* UUID of resource pool (or other pointer to resource data)

=== Composite Resource Pool Methods

When operating on a resource as an object, the following methods
SHALL be supported

Size:: A method to query the current size of a resource pool SHALL 
 be provided.

Allocated:: A method to query the number of objects _allocated_ to
 jobs from the current pool SHALL be provided.

Available:: A method to query the current amount of available members
 in a resource pool object SHALL be provided. The _available_ count
 MAY be calculated as _size_ - _allocated_.

Allocate (N, S):: Allocate _N_ resources from the pool
 under the name _S. The available resources in a pool is
 its size minus the total number of allocations. The allocation
 _S SHALL be stored as a searchable attribute along with
 the resource for later use with _Find_ and _Match_ methods. If an
 allocation under _S already exists, then the allocation
 SHALL be grown by amount _N_.

Free (S, [N]):: Free the allocation named _string_ from the current
 pool and return all allocated items to the list of available resources.
 Optional argument _N_ SHALL shrink the allocation by _N_ items, where
 _N_ is less than or equal to total allocation under name _S_.

Tag (K, [V]):: A method for tagging resource pools with
 arbitrary key/value pairs SHALL be provided. The value _V_ SHALL
 be optional.

Aggregation:: A method for returning resource contents of composite object
 _in aggregate_ SHALL be provided. The aggregate method MAY be implemented
 by traversing all nodes of hierarchy rooted at the current object and
 accumulating the sum of available resources by type name. Resources with
 an available count of 0 SHALL be pruned from the traversal by default,
 since the composite model implies that all children of an unavailable
 resource are themselves not available.

Traversal:: A method for traversal SHALL be provided to visit each node
 in the hierarchy rooted at the current object. The traversal method SHALL
 allow for optionally provided methods for determining the traversal
 pattern for each child resources. This interface SHALL allow, at least,
 the pruning of non-matching subtrees and the order of visitation of
 children during traversal.

Match:: A method or set of methods for resource pool matching
 SHALL be provided by the implementation. Resource pools SHALL
 be matched on tags, properties, size, type, name, basename, 
 ids, etc.

Find:: A search method SHALL be provided by the implementation to 
 traverse the tree and return all matching resource pools, along with
 their children, as well as ancestors up to the root of the hierarchy.
 The _find_ method MAY be implemented as a combination of _traversal_
 and _match_.

Copy:: A method for copying a resource composite to a new instance SHALL
 be provided. This method MAY be used to create a new instance of
 resource description to pass to a sub-job within a Flux instance. The basic
 Copy operation SHALL copy the tree rooted at the current resource,
 pruned of all unavailable resources, as well as all resources
 back to the root of the hierarchy. When copying a resource to a new
 instance, the implementation SHALL copy only _available_ resources
 to the new instance. That is, resource pools with no available
 resources (and their children) SHALL be ignored during a copy,
 and copied resources will have _size_ set to _available_ and
 _allocated_ set to zero.

Duplicate:: A method for duplicating an entire hierarchy SHALL be 
 provided. This method SHALL return a copy of of an existing hierarchy
 without any other unecessary changes.

Merge:: A method for merging one Resource Pool into another SHALL be
 provided. The _merge_ method SHALL allow a Resource Pool at one URI
 to be merged with another Resource Pool Hierarchy at a specified
 ``path'' or new URI. The method SHALL attach the new hierarchy at
 the common ancestor. This method MAY be used by the implementation
 to grow a job resource pool, as in a grow operation for a job.

Unlink:: A method for removing or ``unlinking'' a resource from a hierarchy
 SHALL be provided. This method SHALL remove the current resource from
 the _children_ list of its parent, and remove the current hierarchy
 or topology from the Hierarchy table in the corresponding Resource pool
 data table. If there are no more entries in this Resource's Hierarchy
 table, then the Resource data object MAY be garbage collected.

Serialize:: A method for serializing/deserializing a resource pool and its
 children SHALL be provided to allow for transmission for resource pool
 hierarchy and data over the wire, saving state to a file, etc.

