ifdef::env-github[:outfilesuffix: .adoc]

18/KVS Event Log Format
=======================

This specification describes the format for Flux KVS Event Logs.

* Name: github.com/flux-framework/rfc/spec_18.adoc
* Editor: Stephen Herbein <sherbein@llnl.gov>
* State: raw

== Language

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD",
"SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to
be interpreted as described in http://tools.ietf.org/html/rfc2119[RFC 2119].

== Related Standards

*  link:spec_21{outfilesuffix}[21/Job States and Events]

== Background

The initial use case for Flux KVS Event Logs is recording events
that cause Flux job state transitions, for historical and
synchronization purposes.  These events are defined in detail
in RFC 21.

KVS atomic append capability enables multiple writers to add events to
a single Flux Event Log in a race-free manner.  KVS watch capability
enables a Flux Event Log to be used for synchronization.

== Event Log Format

An event log SHALL be append-only.  An event appended to a KVS event log
MUST take the following form:

----
timestamp name [context ...]\n
----

Where:

* `timestamp` SHALL be the number of seconds since the Unix Epoch (1970-01-01
  UTC), expressed with optional sub-second precision in decimal notation.
  It MUST be greater than zero.  This field is REQUIRED.
* `name` SHALL be a string denoting the name of the event.  It MUST NOT contain
  the space character or the newline character, and SHALL be between one
  and 64 characters in length.  This field is REQUIRED.
* `context` SHALL be a string providing additional arguments or description
  of the event.  It MUST NOT contain the newline character, and SHALL be
  between one and 256 characters in length.  This field is OPTIONAL.

The elements (i.e., timestamp, name, and context) within a single event are
spaced-delimited, and events themselves are newline terminated.
