ifdef::env-github[:outfilesuffix: .adoc]

11/Key Value Store Tree Object Format v1
========================================

The Flux Key Value Store (KVS) implements hierarchical key namespaces
layered atop the content storage service described in RFC 10.
Namespaces are organized as hash trees of content-addressed _tree objects_
and values.  This specification defines the version 1 format of key value
store tree objects.

* Name: github.com/flux-framework/rfc/spec_11.adoc
* Editor: Jim Garlick <garlick@llnl.gov>
* State: raw

== Language

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD",
"SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to
be interpreted as described in http://tools.ietf.org/html/rfc2119[RFC 2119].

== Related Standards

*  link:spec_10{outfilesuffix}[10/Content Storage Service]

== Goals

* Facilitate services implementing private KVS namespaces.
* Users may directly walk a KVS namespace, starting with a blobref/treeref.
* Tree objects can be exchanged between Flux instances.
* Tree objects can be parsed years after they were written (provenance).
* Values exceeding the blob size limit (RFC 10) can be represented.
* Tree objects exceeding the blob size limit (RFC 10) can be represented.
* Values support an append operation.
* A KVS namespace of arbitrary depth can be "rolled up" into one tree object.
* Tree objects are (somewhat) self-describing.
* Large directories are not expensive to access or update.

== Implementation

All tree objects SHALL be represented as JSON objects containing three top
level names:

* _ver_, an integer version number
* _type_, a string type name
* _data_, a type dependent JSON object

There are six types:

* _valref_, data is an array of blobrefs comprising opaque data
* _dirref_, data is an array of blobrefs comprising a _dir_ or _hdir_ object
* _dir_, data is a map of names to tree objects
* _hdir_, data is a map of integer-hashed names to _dirref_ objects
* _symlink_, data is a hierarchical key name
* _value_, data is an arbitrary JSON object, array, or value

=== Valref ===

----
{ "ver":1,
  "type":"valref",
  "data":["sha1-aaa...","sha1-bbb...",...],
}
----

=== Dirref ===

----
{ "ver":1,
  "type":"dirref",
  "data":["sha1-aaa...","sha1-bbb...",...],
}
----

=== Dir ===

----
{ "ver":1,
  "type":"dir",
  "data":{
     "a":{"ver":1,"type":"dirref","data":["sha1-aaa"]},
     "b":{"ver":1,"type":"value","data":42}
     "c":{"ver":1,"type":"valref","data":["sha1-aaa","sha1-bbb"]},
     "d":{"ver":1,"type":"dir","data":{...},
  }
}
----

=== Hdir ===

A _dir_ SHALL be converted to an _hdir_ once the number of entries exceeds
a configurable _maxdirent_ value.  The _hdir_ SHALL have a fixed number of
buckets represented by _size_, fixed when the _hdir_ is created.  The hash
function used to map keys to buckets SHALL be identified with _func_.
Hash buckets MAY be sparsely populated.  Each hash bucket contains a single
_dirref_ object.

----
{ "ver":1,
  "type":"hdir",
  "data":{
    "size":8,
    "func":"city32",
    "bucket":[
      {"ver":1,"type":"dirref","data":["sha1-aaa"]},
      ,,,,,
      {"ver":1,"type":"dirref","data":["sha1-eee"]},
      {"ver":1,"type":"dirref","data":["sha1-fff"]},
    ]
  }
}
----

=== Symlink ===

----
{ "ver":1,
  "type":"symlink",
  "data":"a.aa",
}
----

=== Value ===

----
{ "ver":1,
  "type":"value",
  "data":42,
}
----


