4/Flux Resource Model
=====================

The Flux Resource Model describes the conceptual model used for
resources within the Flux framework.

* Name: github.com/flux-framework/rfc/spec_4.adoc
* Editor: Mark Grondona <mgrondona@llnl.gov>
* State: draft

== Language

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD",
"SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to
be interpreted as described in http://tools.ietf.org/html/rfc2119[RFC 2119].

== Background

As in traditional resource management software, the Flux framework
requires a method for the description, configuration, tracking, and
assignment of consumable and other resources in the system
being managed. The Flux Framework, however, requires a more generalized and
flexible definition of resources and overall approach. This document
describes the basic concepts used to describe each individual
resource and its relationship with other resources. Further, it illustrates
how Flux uses these concepts to model some of the common high performance
computing (HPC) resources in relation to other resource management components.
We term the model for describing resources in Flux
_The Flux Resource Model_.

== Goals

The Flux Resource Model provides a common conceptual model for resources
described and managed by the Flux framework and its components. The
goals of this model are to:

* Develop a generalized, extensible model for resources within the framework
  such that all present and future resource types fit the model
* Provide a common configuration scheme for these resources
* Provide a common storage, access, modification and discovery APIs for
  managing resource information

== Related Standards

link:spec_14{outfilesuffix}[14/Canonical Job Specification]

== The Flux Resource Model

The Flux Resource Model combines two basic concepts to describe
individual resources and various relationships bewteen them.  

The basic concept to describe each individual resource
SHALL be called _resource pool_. A resource pool SHALL allow
the grouping of 1 or more _indistinct_ resources into a pool
with a given size.

The Flux Resource Model SHALL use a graph as its basic concept
to describe relationships among individual resources.
A graph SHALL consist of a set of vertices and edges, and
each vertex SHALL represent a resource pool and an edge
between two vertices SHALL represent a relationship between
them. Each edge MAY be named such a way that the set 
of the same namded edges and the vertices connected by
these edges MAY represent a resource set comprising
a subsystem or simply a system. 

The most common system of resources SHALL be called _composite
resource pool_. A composite resource pool is a set of
resource pools that are hierarchically related through
the _composite_ relationships, i.e., resources with 0
or more children arranged in a hierarchical ``has-a''
relationship.

The composite resource pool SHALL lead to the natural representation of
resources in Flux as a hierarchy of individual or pooled resources
bound to a _root_ which will typically be a ``cluster'' or ``center''
resource.

A common subsystem of resources used in Flux MAY a tree graph
representing a hierarchy. However, 




vertices and edges 


 A vertex in a graph SHALL represent an
individual resource, i.e., a resource pool, and a directed edge
between two vertices SHALL represent a relationship between
two individual resources.  While a common form used in Flux is
a tree graph to capture a hierarhical relaitionship among resources,
more complex graph forms MAY be supported. An individual resource
MAY belong to one or more distinct vertices.

==== Resource Pool Data

* Type
* UUID (Unique ID for this resource)
* Basename
* Name
* ID (optional numeric ID to be appended to basename to get name)
* Properties (static properties associated with this instance)
* Size (Total number of resources in this pool)
* Units (optional units associated with the `size` value)

The default value for `basename` is the `type`.  The default value for
`name` is a concatenation of `basename` and `ID`, or just `basename`
when the `ID` value is not assigned.

The value for `name` SHALL support arbitrary resource attributes and
properties (e.g. a system might have node names formatted like
"node-${frameid}-${rack}").

The value for `properties` SHALL support multiple identifying
properties which could be used to uniquely characterize the resource.



==== Resource Pool Data

* Type
* UUID (Unique ID for this resource)
* Basename
* Name
* ID (optional numeric ID to be appended to basename to get name)
* Properties (static properties associated with this instance)
* Size (Total number of resources in this pool)
* Units (optional units associated with the `size` value)

The default value for `basename` is the `type`.  The default value for
`name` is a concatenation of `basename` and `ID`, or just `basename`
when the `ID` value is not assigned.

The value for `name` SHALL support arbitrary resource attributes and
properties (e.g. a system might have node names formatted like
"node-${frameid}-${rack}").

The value for `properties` SHALL support multiple identifying
properties which could be used to uniquely characterize the resource.

==== Graph Data

TBD: Vertex and Annodated Edges

== Concrete Compositions 

The sections below details how Flux composes the above concepts
to describe some of the common HPC resources.

=== The Composite Resource Pool

A dominant instance of the Flux Resource Model is called
the _composite resource pool_, the combination of a _composite type_ 
(resources with 0 or more children arranged in a hierarchical
``has-a'' graph relationship), and a _resource pool_.

The composite resource pool leads to the natural representation of
resources in Flux as a hierarchy of individual or pooled resources
bound to a _root_ which will typically be a ``cluster'' or ``center''
resource.

Use of the composite resource pool in Flux has the following nice properties:

* Groups of related resources are treated the same as a single instance
* A subset of a composite resource pool is a valid composite resource pool
* Composite resource naturally describes resources in a ``has-a'' relationship
* High level resources can be created piece-wise from base resource types.

=== Composite Resource Pool Representation

The representation of resources within the Flux framework SHALL
allow resources to be modeled as _composite pools_, and thus SHALL
store basic resource _pool_ data (attributes of resource) as well
as _composite_ data (hierarchical parent/child or ``has-a'' relationship
between resources).  Data required to be stored, tracked, and queried
is detailed in sections below.

The Flux Resource Model SHALL support a range of resource sets, from
all of the resources in the center to a small subset allocated to one
Flux instance.

The Flux Resource Model SHALL support multi-granularity scheduling and
management schemes. In such a scheme, the higher the Flux instance is
in the Flux hierarchy, the coarser resource granularity it MAY be
configured to operate at. For example, a higher-order Flux instance
MAY be configured to operate at the racks and aggregates on their
containing nodes while a lower-level instance MAY actually operate at
the nodes and cores as the finest resource granularity.

==== Resource Pool Data

* Type
* UUID (Unique ID for this resource)
* Basename
* Name
* ID (optional numeric ID to be appended to basename to get name)
* Properties (static properties associated with this instance)
* Size (Total number of resources in this pool)
* Units (optional units associated with the `size` value)

The default value for `basename` is the `type`.  The default value for
`name` is a concatenation of `basename` and `ID`, or just `basename`
when the `ID` value is not assigned.

The value for `name` SHALL support arbitrary resource attributes and
properties (e.g. a system might have node names formatted like
"node-${frameid}-${rack}").

The value for `properties` SHALL support multiple identifying
properties which could be used to uniquely characterize the resource.

==== Resource Transient Data

* Tags (dynamic list of tags)
* State (e.g., up, down, degraded, failing, unknown, null)

==== Resource Pool Representation 

Resource pools MAY be associated with other resource pools in
relationships that SHALL be modeled by graphs.  This include the
composite ``has-a'' relationship.  Other examples include graphs that
model power distribution or network topology.

=== Composite Resource Pool Methods

When operating on a resource as an object, the following methods
SHALL be supported

Size:: A method to query the current size of a resource pool SHALL
 be provided.

Tag (K, [V]):: A method for tagging resource pools with
 arbitrary key/value pairs SHALL be provided. The value _V_ SHALL
 be optional.

State:: Methods for setting and returning the state of the resource
 SHALL be provided.

Match:: A method or set of methods for resource pool matching
 SHALL be provided by the implementation. Resource pools SHALL
 be matched on tags, properties, size, type, name, basename,
 ids, etc.

Find:: A search method SHALL be provided by the implementation to
 return all matching resource pools.

Duplicate:: A method for duplicating an entire hierarchy SHALL be
 provided. This method SHALL return a copy of of an existing hierarchy
 without any other unnecessary changes.

Serialize:: A method for serializing/deserializing a resource pool and its
 children SHALL be provided to allow for transmission for resource pool
 hierarchy and data over the wire, saving state to a file, etc.
