ifdef::env-github[:outfilesuffix: .adoc]

16/KVS Job Schema
=================

This specification describes the format of data stored in the KVS
for Flux jobs.

* Name: github.com/flux-framework/rfc/spec_16.adoc
* Editor: Jim Garlick <garlick@llnl.gov>
* State: raw

== Language

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD",
"SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to
be interpreted as described in http://tools.ietf.org/html/rfc2119[RFC 2119].

== Related Standards

*  link:spec_12{outfilesuffix}[12/Flux Security Architecture]
*  link:spec_18{outfilesuffix}[18/KVS Event Log Format]
*  link:spec_21{outfilesuffix}[21/Job States]

== Background

=== Components that use the KVS job schema

Instance components have direct, read/write access to the primary KVS
namespace:

* _Ingest agent_
* _Job manager_
* _Exec service_
* _Scheduler_

Guest components have direct, read/write access to a private KVS namespace:

* _Job shell_
* _User tasks_
* _Command line tools_

=== Job Life Cycle

A job is submitted to the _ingest agent_ which validates jobspec, adds
the job to the KVS, and informs the _job manager_ of the new job.
Upon success, the jobid is returned to the user.  The _job manager_ then
takes the active role in moving a job through its life cycle:

1) If a job has dependencies, interacting with a job dependency
subsystem to ensure they are met before proceeding.

2) Submitting an allocation request to the _scheduler_ to obtain resources.

3) Once resources are allocated, submitting a start request to the
_exec service_.

4) The _exec service_ starts _job shells_ directly in a single-user instance.
In a multi-user instance, it directs the IMP to start them with guest
credentials, with appropriate containment.

5) The _job shell_ examines jobspec and allocated resource set, then
launches tasks on local resources.  It provides standard I/O, parallel
bootstrap, signal propagation, and exit code collection services.
It is a user-replaceable component.

6) Once tasks exit, or an exceptional condition such as cancellation or
expiration of wall clock allocation occurs, the _job manager_ directs the
_exec service_ to clean up any lingering tasks and _job shells_, then
frees resources back to the _scheduler_.

The job is now complete.

== Implementation

=== Primary KVS Namespace

The Flux instance has a default, shared namespace that is accessible
only by the instance owner.

All job data is stored under a `jobs` directory in the primary namespace.


=== Active vs Inactive Job Directories

Each active job has a directory under `jobs.active.<jobid>`,
where `<jobid>` is a unique sequence number assigned by the
_ingest agent_.

After a job is no longer active, its directory is moved from
`jobs.active` to `jobs.inactive`.  Inactive means its state
is read-only.  The purpose of moving inactive jobs to another
directory is to permit recovery of the active job queue from the KVS
during a restart, and keep the size of the active directory manageable.
The `jobs.inactive` directory may need to be periodically archived
and purged to keep its size manageable in long-running instances.


=== Guest KVS Namespace

A guest-writable KVS namespace is created by the _exec service_
for the use of the _job shell_ and the application.  While the job
is active, this namespace is linked from `jobs.active.<jobid>.guest`
in the primary KVS namespace.  While linked, it can be changed
by the guest components without impacting performance of the primary
namespace, while still being accessible through the link in the
primary namespace.

When the job transitions to inactive, the final snapshot of the
guest namespace content is linked by the _exec service_ into the primary
namespace, and the guest namespace is destroyed.


=== Access to Primary Namespace by Guest Users

Guests may access data in the primary KVS namespace only through instance
services that allow selective guest access, by proxy or by staging copies
to the guest namespace.


=== Event Log

Active jobs undergo change represented as events that are recorded under
the key `jobs.active.<jobid>.eventlog`.  A KVS append operation
is used to add events to this log.

Each append consists of a string matching the format described in
link:spec_18{outfilesuffix}[RFC 18/KVS Event Log Format].


=== Content Produced by Ingest Agent

A user submits _J_ with attached signature.

The _ingest agent_ validates _J_ and if accepted, populates the KVS with:

`jobs.active.<jobid>.J`::
signed user request token for passing to IMP in a multi-user instance.

`jobs.active.<jobid>.jobspec`::
jobspec in JSON form

`jobs.active.<jobid>.eventlog`::
eventlog described above

The _ingest agent_ logs one event to the eventlog:

`submit` `userid=UID priority=N`::
job was submitted, with authenticated userid and priority (0-31)


=== Content Consumed/Produced by Job Manager

Upon notification of a new `jobs.active.<jobid>`, the _job manager_ takes
the active role in moving a job through its life cycle, and logs events
to the eventlog as described in RFC 21.

When a job becomes inactive, the _job manager_ moves it to
`jobs.inactive`.

When the _job manager_ is restarted, it recovers its state by scanning
`jobs.active` and replaying the eventlog for each job found there.


=== Content Consumed/Produced by Scheduler

When the _scheduler_ receives an allocation request containing a jobid,
it reads the jobspec from `jobs.active.<jobid>.jobspec`.

The scheduler allocates resources by writing a resource set
to `jobs.active.<jobid>.R` and answering the allocation request.

The scheduler frees resources by answering the free request,
leaving `R` in place for job provenance.  During a restart, the
_job manager_ uses the eventlog to determine whether `R` is currently
allocated.


=== Content Consumed/Produced by Exec Service

When the _exec system_ receives a start request containing a jobid,
it reads the `jobs.active.<jobid>.R` and `jobs.active.<jobid>.jobspec`
and uses this information to launch _job shells_ and subsequently tasks.

The _exec system_ creates the job's guest namespace and links it to
`jobs.active.<jobid>.guest`.  Its initial contents are populated with

`exec.R`::
copy of `jobs.active.<jobid>.R`

`exec.jobspec`::
copy of `jobs.active.<jobid>.jobspec`

`exec.eventlog`::
An eventlog for the use of _job shells_, TBD.


=== Content Produced/Consumed by Other Instance Services

Other services not mentioned in this RFC MAY store arbitrary data associated
with jobs under the `jobs.active.<jobid>.data.<service>` directory,
where `<service>` is a name unique to the service producing the data.
For example, a job tracing service may store persistent trace data under
the `jobs.active.<jobid>.data.trace` directory.


=== Content Consumed/Produced by Other Guest Services ===

Other guest services not mentioned in this RFC MAY store service-specific
data in the guest KVS namespace under `<service>`, where `<service>` is
a name unique to the service producing the data.

=== Content Consumed/Produced by the Application ===

The application MAY store application-specific data in the guest KVS
namespace under `application`.

When the application is another Flux instance, `exec.R` MAY be used
to initialize the resource set managed by the instance.

=== Content Consumed/Produced by Tools

Tools such as parallel debuggers, running as the guest, MAY store data
in the guest KVS namespace under `tools.<name>`, where `<name>` is
a name unique to the tool producing the data.
