ifdef::env-github[:outfilesuffix: .adoc]

7/Flux Coding Style Guide
=========================

This specification presents the recommended standards when contributing code to the Flux code base.

* Name: github.com/flux-framework/rfc/spec_7.adoc
* Editor: Don Lipari <lipari@llnl.gov>
* State: draft

== Language

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD",
"SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to
be interpreted as described in http://tools.ietf.org/html/rfc2119[RFC 2119].

== Related Standards

* https://www.kernel.org/doc/Documentation/CodingStyle

== Goals

* Encourage a uniform coding style in flux-framework projects
* Provide a document to reference when providing style feedback in project pull requests

== C Coding Style Recommendations

Flux projects written in C SHOULD conform to the C99 version of the language.

In general, Flux follows the "Kernighan & Ritchie coding style" with the following exceptions or examples:

1. Indenting SHOULD be with spaces, and not tabs.
2. One level of indentation SHOULD be 4 spaces.
3. One space SHOULD separate function names and the opening parenthesis (enhances readability).
4. There SHOULD be no trailing spaces (or tabs) after the last non-space character in a line.
5. Lines SHOULD be limited to 80 characters.
6. Comments SHOULD be indented to the depth of the code they are describing.
7. The return type SHOULD be on the same line as the function declaration.
8. One space SHOULD separate the star and type in pointer declarations.  Example:
----
int *ptr;
----

=== Variable Names

Variable names SHOULD NOT include upper case letters.
For example `msg_count` is OK, but `MsgCount` or `MSG_COUNT` do not conform.

Preprocessor macro names SHOULD NOT include lower case letters. 
For example `FLUX_FOO_MAGIC` is OK but `flux_foo_magic` and `FluxFooMagic` do not conform.

=== Typedefs

C typedef names SHOULD NOT include upper case letters.

C typedef names for functions SHOULD end in `_f` and SHOULD be defined as function pointers, for example:
----
typedef int (*flux_foo_f)(int arg1, int arg2);
----

C typedef names for non-functions SHOULD end in `_t`, for example:
----
typedef int my_type_t;
----

Abstract types SHOULD be publicly defined as incomplete types, for example:
----
typedef struct foo foo_t;
----
Abstract types SHOULD NOT be defined as pointers to incomplete types,

Typedef names SHOULD be chosen such that they are unique within a framework project.
For example avoid generic types like `struct a` or typedefs like `ctx_t`. A good
practice is to include the name of the relevant source file, module or service in
the typedef (e.g. `fooservice_ctx_t`).

=== Structures

Structure tags SHOULD NOT contain the string "struct".

In the same way that we would not write:
----
int count_int;
float val_float;
----
we also should not write:
----
struct foo_struct {};
----

Tools That Modify Code to Conform to C Coding Style
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"indent -kr" will bring you most of the way towards conforming to the Flux coding style.

Those using vi will automatically follow some of the Flux style based on the presence of the following at the end of each file:

----
/*
 * vi:tabstop=4 shiftwidth=4 expandtab
 */
----

In vim, use the following to highlight whitespace errors:

----
let c_space_errors = 1
----

In emacs, add this to your custom-set-variables defs to highlight whitespace errors:

----
'(show-trailing-whitespace t)
----

For astyle, the pertinent options would be:
----
--indent-coll-comments --style=stroustrup --indent-spaces=4
 --align-pointer=name --max-code-length=80 --convert-tabs
----
